# Generated by Django 5.2.4 on 2025-08-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time_range', models.CharField(help_text='Vaqt oraliği, masalan: 14:00 – 15:00', max_length=50)),
                ('venue', models.CharField(help_text='Tadbir o‘tkaziladigan joy nomi', max_length=200)),
                ('location', models.CharField(blank=True, help_text='Manzil (ixtiyoriy)', max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PLANNED', 'Rejalashtirilgan'), ('COMPLETED', 'Tugagan')], default='PLANNED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-time_range'],
            },
        ),
    ]
