# Generated by Django 5.2.4 on 2025-08-03 04:38

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=1000)),
                ('programmes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmesdata_set', to='Universities.programmes')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=1000)),
                ('programmes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirementsdata_set', to='Universities.requirements')),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=1000)),
                ('programmes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmesdata_set', to='Universities.scholarships')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='media/universities/')),
                ('yt_video_link', models.URLField(blank=True, null=True)),
                ('ranking', models.PositiveIntegerField(db_index=True)),
                ('description', models.TextField()),
                ('details_url', models.URLField(unique=True)),
                ('programmes', models.CharField(max_length=1000, null=True)),
                ('scholarships', models.CharField(max_length=1000, null=True)),
                ('requirements', models.CharField(max_length=1000, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='Universities.country')),
            ],
        ),
        migrations.CreateModel(
            name='ShortInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bgColor', colorfield.fields.ColorField(default='#3498db', image_field=None, max_length=25, samples=None)),
                ('fontColor', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('priority', models.PositiveIntegerField(default=10)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_info', to='Universities.university')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.AddField(
            model_name='scholarships',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_set', to='Universities.university'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_set', to='Universities.university'),
        ),
        migrations.AddField(
            model_name='programmes',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_set', to='Universities.university'),
        ),
        migrations.CreateModel(
            name='ExtraParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_paragraphs', to='Universities.university')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('text', models.TextField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose', to='Universities.university')),
            ],
        ),
    ]
