# Generated by Django 5.2.4 on 2025-08-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
