# Generated by Django 5.2.4 on 2025-08-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
