# Generated by Django 5.2.4 on 2025-08-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('telegram_nickname', models.CharField(blank=True, max_length=32)),
                ('wanted_country_of_study', models.CharField(max_length=64)),
                ('study_program', models.CharField(max_length=128)),
                ('planning_money', models.DecimalField(decimal_places=2, max_digits=12)),
                ('text_message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
